### ISSUE TITLE
Сделать возможным кастомизацию OkHttpClient'а, который используется OkHttpOpenApi

### ISSUE THREAD

**Issue by evgeniymelnikov** [Tinkoff/invest-openapi-java-sdk#132]
https://github.com/TinkoffCreditSystems/invest-openapi-java-sdk/blob/master/sdk-java8/src/main/java/ru/tinkoff/invest/openapi/okhttp/OkHttpOpenApi.java#L31
Из-за инициализации OkHttpClient внутри конструктора OkHttpOpenApi исключается возможность кастомизации (включая добавления интерцепторов, которые, в частности, позволяют легко реализовать соблюдение rate limiter'а).

**Варианты**:
Добавить конструктор с наличием среди параметров OkHttpClient'а или консумера java.util.function.Consumer<OkHttpClient.Builder>, который позволит кастомизировать клиент.

Сейчас в качестве workaround'а приходится пользоваться рефлексией и подменять OkHttpClient.

**Comment by mitaichik** [comment]
Плюсую. В любой либе где юзается OkHttp имеется возможность его кастомизации.

**Comment by zlumyo** [comment]
Закрываю тикет в связи с заморозкой репозитория
