### ISSUE TITLE
Улучшение интервалов по свечам

### ISSUE THREAD

**Issue by Freeongoo** [Tinkoff/invest-openapi-java-sdk#143]
1. Устранить два одинаковых Enum: `ru.tinkoff.invest.openapi.model.res.CandleResolution` и `ru.tinkoff.invest.openapi.model.stream.CandleInterval`, не вижу ни одной причины зачем использовать два Enum.
2. Использовать более расширенный Enum `ru.tinkoff.invest.openapi.model.stream.CandleInterval` в качестве основного, поскольку в `ru.tinkoff.invest.openapi.model.res.CandleResolution` нет интервала 4hour а он очень нужен для технического анализа.

**Comment by zlumyo** [comment]
Enum из пакета `model.rest` сгенерирован. Придётся отказаться от генерации моделей из сваггера целиком. Расширенный Enum использовать не совсем корректно, поскольку при использовании 4hour будет возникать ошибка.
Это проблема скорее на уровне API, а не SDK. Думаю, лучше обратиться с этим вопросом в [соответствующий репозиторий](https://github.com/Tinkoff/investAPI). Хотя сейчас готовится к выпуску API версии 2.0, где всё поменяется, поэтому вряд ли в текущей версии эту проблему устранят.
