### ISSUE TITLE
/portfolio API doesn't allow to distinguish LONG and SHORT positions

### ISSUE THREAD

**Issue by selivonchyk** [Tinkoff/invest-openapi-java-sdk#148]
There is no info in response to /portfolio API that would allow to understand whether the position is LONG or SHORT. 
Please add new field to position object indicating position side or at least make balance negative for SHORT positions.

**Comment by zlumyo** [comment]
It's a feature request at API level. Please open issue in [API repo](https://github.com/Tinkoff/investAPI).
