### ISSUE TITLE
При сборке ошибка Unable to read URL: https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/swagger.yaml

### ISSUE THREAD

**Issue by demen777** [Tinkoff/invest-openapi-java-sdk#149]
При сборке с помощью mvn clean package фиксируется ошибка:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ru.tinkoff.invest:openapi-java-sdk 0.6-SNAPSHOT:
[INFO]
[INFO] ru.tinkoff.invest:openapi-java-sdk ................. SUCCESS [  6.293 s]
[INFO] ru.tinkoff.invest:openapi-java-sdk-core ............ FAILURE [  6.894 s]
[INFO] ru.tinkoff.invest:openapi-java-sdk-java8 ........... SKIPPED
[INFO] ru.tinkoff.invest:openapi-java-sdk-example ......... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.384 s
[INFO] Finished at: 2022-01-14T08:29:27+05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.swagger.codegen.v3:swagger-codegen-maven-plugin:3.0.29:generate (default) on project openapi-java-sdk-core: Execution default of goal io.swagger.codegen.v3:swagger-codegen-maven-plugin:3.0.29:generate failed: Unable to read URL: https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/swagger.yaml -> [Help 1]

Вероятно задан несуществующий на текущий момент URL для swagger.yaml

**Comment by AlexanderVolkovTCS** [comment]
@zlumyo можно поменять на https://tinkoff.github.io/invest-openapi/swagger-ui/swagger.yaml  ?
Название организации изменилось

**Comment by zlumyo** [comment]
> @zlumyo можно поменять на https://tinkoff.github.io/invest-openapi/swagger-ui/swagger.yaml ? Название организации изменилось

Ок, поменяем

**Comment by zlumyo** [comment]
Выпущен релиз 0.5.2 с заменой адреса на новый.
