### ISSUE TITLE
Как проверить тип исторической операции, когда операция помечена как 'обрабатывается'

### ISSUE THREAD

**Issue by Freeongoo** [Tinkoff/invest-openapi-java-sdk#150]
Никак не могу понять, как определить, что совершенная операция по тикету выполняется, но еще не исполнена, а в состоянии 'обрабатывается' (желтые часы)

Получается для этой операции нельзя определить тип операции (OperationTypeWithCommission) покупка это выполняется или продажа?

**Comment by zlumyo** [comment]
В текущем варианте API нет возможности (SDK тут никак не поможет). Этот вопрос лучше задать в [репо самого Invest API](https://github.com/Tinkoff/invest-openapi).
